name-template: 'Release Notes'
tag-template: 'Draft'
categories:
  - title: ' New Features'
    labels:
      - 'features'
      - 'tests'
  - title: ' Bugs Fixes'
    labels:
      - 'fix'
  - title: ' Documentation'
    labels:
      - 'documentation'
  - title: ' Configuration'
    labels:
      - 'config'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES