name: Example of simple Java CI
on:
  push:
    branches:
        - main
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: temurin
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.5

    - name: Execute Gradle build
      run: ./gradlew build

  weather:
    runs-on: ubuntu-22.04
    steps:
      - name: Weather Call
        uses: andreilisa/python-custom-actions@v.1.0.0
        with:
          city_name: ${{ env.CITY_NAME }}
          open_weather_key: ${{ secrets.OPEN_WEATHER_KEY }}
