name: "Verify type labels"
on:
  pull_request:
    types:
       - opened
       - labeled
       - unlabeled
jobs:
  triage:
    runs-on: ubuntu-22.04
    steps:
      - uses: zwaldowski/match-label-action@v2
        with:
          allowed: 'fix, features, documentation, tests, config, dependencies'
  reusable-invoke:
    uses: ./.github/workflows/reusable-workflow.yml
