name: Add comment on Issue
on:
  issues:
    types:
      - opened
jobs:
  add-comment:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            Thank you for opening this issue
  reusable-invoke:
    uses: https://github.com/andreilisa/githubactions/actions/workflows/reusable-workflow.yml@main