name: PR Comment

on:
  pull_request:
    types:
      - opened

jobs:
  PR-Comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: PR Comment
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':warning:  Message'
            })