on:
  pull_request:

jobs:
  build:
    name: Comment a pull_request
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'Slava' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Hello, Thank you for this PR!"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}