name: Telegram notification

on:
  pull_request:
    branches:
      - main

jobs:
  telegram-notification:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            A new PR is raised [View all PR's](https://github.com/andreilisa/githubactions/pulls)